version: '3.8'
services:
  app:
    container_name: cortextask
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  #
    env_file:
      - app.env
    depends_on:
      - db
      - flyway
    restart: on-failure
    entrypoint: ["sh", "-c", "sleep 120 && java -jar app.jar"]

  flyway:
    image: flyway/flyway:7.10.0
    depends_on:
      - db
    volumes:
      - ./src/main/resources/db/migration:/flyway/sql
    env_file:
      - app.env
    entrypoint: ["sh", "-c", "sleep 120 && flyway migrate"]
    restart: on-failure

  db:
    container_name: mysql-db
    image: mysql:8.0
    env_file:
      - app.env
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql

volumes:
  db-data:
