apiVersion: v1
kind: Service
metadata:
  name: cortextask
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000 # Or any other port you prefer within the NodePort range
  selector:
    app: cortextask
